package com.taiger.nlp.ner.model;

public enum Period {
	PREHISTORY,
	ANCIENT_AGE,
	MIDDLE_AGE,
	LATE_MIDDLE_AGE, // includes XV
	MODERN_HISTORY_XVI, // includes XV
	MODERN_HISTORY_XVII, // includes XVIII
	CONTEMPORARY_HISTORY_XIX, // includes XVIII
	CONTEMPORARY_HISTORY_XX,
	CONTEMPORARY_HISTORY_XXI,
	UNKNOWN
}
